# Generated by Django 4.2.1 on 2023-07-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=120)),
                ('familya', models.CharField(max_length=120)),
                ('age', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('phone', models.CharField(choices=[('uzb', '+998'), ('rus', '+721'), ('us', '+132')], max_length=13)),
            ],
        ),
    ]
